import { defineConfig } from 'vite'
import { ViteMinifyPlugin } from 'vite-plugin-minify'
import fs from 'node:fs'
import twig from '@vituum/vite-plugin-twig'
import path from 'node:path'
import sassGlobImports from 'vite-plugin-sass-glob-import'
import viteImagemin from 'vite-plugin-imagemin'
import vituum from 'vituum'

import base64 from './helpers/base64'
import classList from './helpers/classList'
import htmlAttr from './helpers/htmlAttr'
import htmlSvg from './helpers/htmlSvg'

// Get root directory
const rootDir = process.cwd()

// Vite config
export default defineConfig({
  base: '/',
  build: {
    assetsInlineLimit: 0,
    emptyOutDir: true,
    modulePreload: false,
    outDir: './dist',
    rollupOptions: {
      input: [
        './src/js/*.js',
        './src/view/**/*.{twig,html}',
      ],
      output: {
        entryFileNames: 'js/[hash].js',
        chunkFileNames: 'js/[hash].js',
        assetFileNames: (assetInfo) => {
          let extType = assetInfo.name.split('.').pop()

          if (/jpe?g|png|svg|gif|webp|ico/i.test(extType)) {
            extType = 'img'
          }

          if (/woff?2|ttf|eot/i.test(extType)) {
            extType = 'font'
          }

          return `${extType}/[hash][extname]`
        },
      },
    },
  },
  css: {
    devSourcemap: true,
    preprocessorOptions: {
      scss: {
        api: 'modern-compiler',
        silenceDeprecations: ['mixed-decls'],
      },
    },
  },
  plugins: [
    vituum({
      pages: {
        dir: './src/view',
      },
    }),
    twig({
      functions: getTwigFunctions(),
      globals: getTwigGlobals(),
      namespaces: getTwigNamespaces(),
      root: './src',
    }),
    sassGlobImports(),
    viteImagemin({
      gifsicle: {
        optimizationLevel: 1,
        interlaced: false,
      },
      optipng: {
        optimizationLevel: 5,
      },
      mozjpeg: {
        quality: 75, progressive: true,
      },
      pngquant: {
        quality: [0.7, 0.9],
        speed: 7,
      },
      svgo: {
        plugins: [
          {
            name: 'removeViewBox',
            active: false,
          },
          {
            name: 'convertShapeToPath',
            active: false,
          },
          {
            name: 'convertEllipseToCircle',
            active: false,
          },
        ],
      },
    }),
    ViteMinifyPlugin({
      collapseWhitespace: true,
      includeAutoGeneratedTags: false,
      minifyCSS: true,
      minifyJS: true,
      removeComments: true,
    }),
  ],
  preview: {
    port: 3000,
    host: true,
  },
  server: {
    port: 5173,
    host: false,
  },
})

function getTwigFunctions() {
  return {
    base64,
    classList,
    htmlAttr,
    htmlSvg,
  }
}

function getTwigGlobals() {
  const data = {}
  const dataFolder = path.join(rootDir, 'src', 'data')

  const dataFiles = fs.readdirSync(dataFolder).filter((file) => file.endsWith('.json')) || []

  dataFiles.forEach((file) => {
    const filePath = path.join(rootDir, 'src', 'data', file)

    const fileContent = fs.readFileSync(filePath, 'utf8') || '{}'

    const fileData = JSON.parse(fileContent)

    const fileName = file.replace('.json', '').replace(/[\s-]+/g, '_').replace(/[^a-z_]+/g, '').replace(/(_)./g, (s) => s.slice(-1).toUpperCase())

    data[fileName] = fileData
  });

  return data
}

function getTwigNamespaces() {
  const list = [
    'assets',
    'components',
    'icons',
    'layouts',
    'objects',
    'partials',
    'templates',
  ]

  return list.reduce((acc, namespace) => {
    return {
      ...acc,
      [namespace]: `./src/includes/${namespace}`
    }
  })
}
